---
swagger: "2.0"
info:
  description: "权限管理服务\n"
  version: "1.0.0"
  title: "AECWorks BIMServer Permission Service"
  termsOfService: "http://www.aecworks.cn/terms/"
  contact:
    email: "apiteam@aecworks.cn"
  license:
    name: "上海开建信息技术有限公司"
    url: "http://www.AECWorks.cn/licenses"
host: "developer-dev.api.bimbox.cn"
basePath: "/permission/v1"
tags:
- name: "Catalog"
  description: "Permission Catalog"
  externalDocs:
    description: "Find out more"
    url: "http://www.aecworks.cn"
schemes:
- "http"
- "https"
paths:
  /catalogs:
    get:
      tags:
      - "Catalog"
      summary: "获取当前 client 所有的 Permission Catalog"
      operationId: "getCatalog"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/PermissionCatalogDataWrapper"
          examples:
            application/json:
              data:
                count: 2
                permissionCatalogs:
                - key: "my_key_1"
                  desctription: "the description for my_key_1"
                - key: "my_key_2"
                  desctription: "the description for my_key_2"
        401:
          description: "无法验证Client的身份，请确认已经登录，并获得有效的Token"
        403:
          description: "当前Client的授权无法访问请求的资源"
    post:
      tags:
      - "Catalog"
      summary: "为当前的 client 创建一个 Permission Catalog"
      operationId: "addCatalog"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "一个完整的 Permission Catalog 对象"
        required: true
        schema:
          $ref: "#/definitions/PermissionCatalog"
      responses:
        401:
          description: "无法验证Client的身份，请确认已经登录，并获得有效的Token"
        403:
          description: "当前Client的授权无法访问请求的资源"
        405:
          description: "catalog key 的格式不对, 接受的字符为：字母，下划线和数字"
          schema:
            $ref: "#/definitions/ErrorModel"
          examples:
            application/json:
              message: "CatalogKeyInvalid:my_key_1"
        409:
          description: "当前的 client 下已经有同名的 catalog key"
          schema:
            $ref: "#/definitions/ErrorModel"
          examples:
            application/json:
              message: "CatalogKeyConflict:my_key_1"
    put:
      tags:
      - "Catalog"
      summary: "为当前的 client 更新指定的 Permission Catalog"
      operationId: "updateCatalog"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "一个完整的 Permission Catalog 对象"
        required: true
        schema:
          $ref: "#/definitions/PermissionCatalog"
      responses:
        401:
          description: "无法验证Client的身份，请确认已经登录，并获得有效的Token"
        403:
          description: "当前Client的授权无法访问请求的资源"
        404:
          description: "catalog key 不存在"
          schema:
            $ref: "#/definitions/ErrorModel"
          examples:
            application/json:
              message: "NoSuchCatalogKey:my_key_1"
definitions:
  PermissionCatalogs:
    type: "object"
    required:
    - "count"
    - "permissionCatalogs"
    properties:
      count:
        type: "integer"
        format: "int32"
      permissionCatalogs:
        type: "array"
        items:
          $ref: "#/definitions/PermissionCatalog"
  PermissionCatalogDataWrapper:
    type: "object"
    required:
    - "data"
    properties:
      data:
        $ref: "#/definitions/PermissionCatalogs"
  PermissionCatalog:
    type: "object"
    required:
    - "key"
    properties:
      key:
        type: "string"
        description: "Permission Catalog的 key， 用来标识和组织一组 Permission。接受的字符为：字母和数字，分\
          隔符为下划线 _ 。第一个字符不能够是下划线 _ 。"
      description:
        type: "string"
        description: "对 Permission Catalog 的简短描述"
    example:
      key: "my_catalog_key"
      desctription: "This key is used by Awesome App"
  ErrorModel:
    required:
    - "message"
    properties:
      message:
        type: "string"
